version: '3.9'

services:
  # mssql
  labccDb:
    container_name: labcc-mssql
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - sql-storage:/var/opt/mssql

volumes:
  sql-storage: