version: '3.9'

services:
  # mssql
  labccDb:
    container_name: labcc-mssql
    restart: no
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"
    networks:
      - labcc_network
  
  #sonarqube
  labcc-sonarqube:
    image: sonarqube:latest
    container_name: backend_sonarqube
    ports:
      - "9000:9000"
    networks:
      - labcc_network
    environment:
      SONARQUBE_JDBC_USERNAME: ${SONARQUBE_USERNAME} 
      SONARQUBE_JDBC_PASSWORD: ${SONARQUBE_PASSWORD} 
      SONAR_JDBC_URL: ${SONAR_JDBC_URL}
  
  #labcc-backend
  labcc-dotnet-backend:
    build:
      context: ../
      dockerfile: ./.devops/dockerfile.aspnet
      args:
        - PROJECT_NAME=LABCC.BackEnd
        - PROJECT_PATH=./
    env_file:
      - ./.env
    container_name: labcc-dotnet-backend
    ports:
      - "${LABCC_BACKEND_PORT}:80" # Mapeamento da porta do contêiner para a porta local (80)
    networks:
      - labcc_network
    depends_on:
      - labccDb
      - labcc-sonarqube

networks:
  labcc_network:
    driver: bridge