// <auto-generated />
using LABCC.BackEnd.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace LABCC.BackEnd.Infrastructure.Migrations
{
    [DbContext(typeof(MsSqlContext))]
    partial class MsSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LABCC.BackEnd.Domain.Entities.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BirthDate = new DateTime(2000, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = 1687441875843L,
                            Document = "278.656.291-09",
                            Email = "lucas_diego@gimail.com",
                            Gender = 0,
                            IsActive = true,
                            Name = "Lucas Diego Santos",
                            Telephone = "(63) 99729-3374",
                            UpdatedAt = 1687441875843L,
                            UserType = 0
                        },
                        new
                        {
                            Id = 2L,
                            BirthDate = new DateTime(2001, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = 1687441875843L,
                            Document = "121.682.363-48",
                            Email = "marcos.mateus.campos@doublesp.com.br",
                            Gender = 0,
                            IsActive = true,
                            Name = "Marcos Mateus Anthony Campos",
                            Telephone = "(75) 99404-5248",
                            UpdatedAt = 1687441875843L,
                            UserType = 3
                        },
                        new
                        {
                            Id = 3L,
                            BirthDate = new DateTime(1954, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = 1687441875843L,
                            Document = "493.617.515-30",
                            Email = "mirella_beatriz_lima@engeseg.com.br",
                            Gender = 1,
                            IsActive = true,
                            Name = "Mirella Beatriz Lima",
                            Telephone = "(62) 98420-9876",
                            UpdatedAt = 1687441875843L,
                            UserType = 0
                        },
                        new
                        {
                            Id = 4L,
                            BirthDate = new DateTime(1996, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = 1687441875843L,
                            Document = "864.306.046-16",
                            Email = "antonio_carlos_dias@lukin4.com.br",
                            Gender = 2,
                            IsActive = true,
                            Name = "Antonio Carlos Eduardo Dias",
                            Telephone = "(65) 99579-0748",
                            UpdatedAt = 1687441875843L,
                            UserType = 1
                        },
                        new
                        {
                            Id = 5L,
                            BirthDate = new DateTime(1998, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = 1687441875843L,
                            Document = "945.981.184-15",
                            Email = "kamilly.antonia.almeida@onset.com.br",
                            Gender = 1,
                            IsActive = true,
                            Name = "Kamilly Antônia Almeida",
                            Telephone = "(93) 98644-1270",
                            UpdatedAt = 1687441875843L,
                            UserType = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
